import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link";

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col bg-gradient-to-b from-background to-muted/30 dark:to-muted/10 selection:bg-primary/20 selection:text-primary" suppressHydrationWarning>
        <header className="sticky top-0 z-50 w-full border-b bg-background/80 backdrop-blur-xl supports-[backdrop-filter]:bg-background/60 shadow-sm">
          <div className="container mx-auto max-w-2xl flex h-14 items-center justify-between px-4">
            <div className="flex items-center gap-2 font-bold tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-primary to-primary/60">
              AI Labs
            </div>
            <nav className="flex items-center gap-6 text-sm font-medium">
              <Link href="/" className="relative transition-colors hover:text-primary text-foreground/70 after:absolute after:bottom-[-16px] after:left-0 after:h-[2px] after:w-0 after:bg-primary after:transition-all hover:after:w-full">Chat</Link>
              <Link href="/image-chat" className="relative transition-colors hover:text-primary text-foreground/70 after:absolute after:bottom-[-16px] after:left-0 after:h-[2px] after:w-0 after:bg-primary after:transition-all hover:after:w-full">Vision</Link>
              <Link href="/feedback" className="relative transition-colors hover:text-primary text-foreground/70 after:absolute after:bottom-[-16px] after:left-0 after:h-[2px] after:w-0 after:bg-primary after:transition-all hover:after:w-full">Feedback</Link>
            </nav>
          </div>
        </header>
        <main className="flex-1 flex flex-col">
          {children}
        </main>
      </body>
    </html>
  );
}
